name: Executing Action between Repositories
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Run Workflow between Repositories
    runs-on: ubuntu-latest
    steps:
      - name: Workflow from one Repo to Another Repo
        run: |
          echo "WorK Flow one Repo  to Another"
          #sleep 10s
      - uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: Vijai Kannan
          repo: hello-world-javascript-action
          #github_token: ${{ secrets.G_ACCESS_TOKEN }}
          workflow_file_name: main.yml
      #- name: Deploy Web App
        #run: |
          #echo "Deploy Web App"
          #sleep 10s